// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dictionary.proto

#include "dictionary.pb.h"
#include "dictionary.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* DictionaryService_method_names[] = {
  "/DictionaryService/ProcessWord",
};

std::unique_ptr< DictionaryService::Stub> DictionaryService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DictionaryService::Stub> stub(new DictionaryService::Stub(channel));
  return stub;
}

DictionaryService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ProcessWord_(DictionaryService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DictionaryService::Stub::ProcessWord(::grpc::ClientContext* context, const ::WordRequest& request, ::WordResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ProcessWord_, context, request, response);
}

void DictionaryService::Stub::experimental_async::ProcessWord(::grpc::ClientContext* context, const ::WordRequest* request, ::WordResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ProcessWord_, context, request, response, std::move(f));
}

void DictionaryService::Stub::experimental_async::ProcessWord(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::WordResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ProcessWord_, context, request, response, std::move(f));
}

void DictionaryService::Stub::experimental_async::ProcessWord(::grpc::ClientContext* context, const ::WordRequest* request, ::WordResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ProcessWord_, context, request, response, reactor);
}

void DictionaryService::Stub::experimental_async::ProcessWord(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::WordResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ProcessWord_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::WordResponse>* DictionaryService::Stub::AsyncProcessWordRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::WordResponse>::Create(channel_.get(), cq, rpcmethod_ProcessWord_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::WordResponse>* DictionaryService::Stub::PrepareAsyncProcessWordRaw(::grpc::ClientContext* context, const ::WordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::WordResponse>::Create(channel_.get(), cq, rpcmethod_ProcessWord_, context, request, false);
}

DictionaryService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DictionaryService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DictionaryService::Service, ::WordRequest, ::WordResponse>(
          [](DictionaryService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::WordRequest* req,
             ::WordResponse* resp) {
               return service->ProcessWord(ctx, req, resp);
             }, this)));
}

DictionaryService::Service::~Service() {
}

::grpc::Status DictionaryService::Service::ProcessWord(::grpc::ServerContext* context, const ::WordRequest* request, ::WordResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


